### ISSUE TITLE
php5.5+mysql5.6

### ISSUE THREAD

**Issue by mytargets** [gouguoyin/phprap#45]
本地wamp环境，按照readme操作，请求public下的index.php报500错误，无法进入安装页面

**Comment by gouguoyin** [comment]
web能访问到吗？

**Comment by batcom** [comment]
一样的我的也是出500调试的是找不到类　web可以访问到

**Comment by batcom** [comment]
你这个经过测试了吗？

**Comment by gouguoyin** [comment]
runtime目录给可读可写权限了吗？

**Comment by gouguoyin** [comment]
@batcom runtime目录给可读可写权限了吗？

**Comment by batcom** [comment]
@gouguoyin 不是权限问题，上个issue 已经调试了是找不到类库，好像是自动加载出问题了。

**Comment by gouguoyin** [comment]
@batcom 你是cli模式运行的吗？php5.5版本我测试过是没问题的，[http://www.phprap.com/doc/business.html](http://www.phprap.com/doc/business.html)这些都是已经部署使用的。

**Comment by batcom** [comment]
＠gouguoyin　帮你看了下是　Linux下面严格区分大小写的问题，估计你是windows或者Mac的开发环境，而我是Linux　最终的原因是因为该项目没有遵循PSR-4规范所导致的.可参考
https://laravel-china.org/articles/3782/a-pit-reminder-a-class-or-a-trait-suddenly-can-not-find
https://www.kancloud.cn/thinkphp/php-fig-psr/3144
最终找不到类文件导致500错误。
我是以php-fpm　方式运行的

**Comment by mytargets** [comment]
@gouguoyin 我是windows环境，gophp/init.php打开错误提示报如下错误,同事php7就没问题

( ! ) Fatal error: Uncaught exception 'gophp\exception' with message 'Class gophp\traits\driver  does not exist' in D:\wamp\www\rap\gophp\library\reflect.php on line 38
( ! ) gophp\exception: Class gophp\traits\driver  does not exist in D:\wamp\www\rap\gophp\library\reflect.php on line 38

# | Time | Memory | Function | Location
1 | 0.0118 | 835776 | gophp\app::shutdownHandler(  ) | ..\app.php:0
2 | 0.0119 | 837152 | gophp\app::show(  ) | ..\app.php:63
3 | 0.0122 | 837768 | gophp\view->assign(  ) | ..\app.php:125
4 | 0.0122 | 837848 | gophp\view->handler(  ) | ..\view.php:46
5 | 0.0122 | 838040 | gophp\reflect::getName(  ) | ..\driver.php:34
6 | 0.0122 | 838040 | gophp\reflect::getClass(  ) | ..\reflect.php:70
7 | 0.0122 | 838040 | gophp\reflect::hasClass(  ) | ..\reflect.php:54

**Comment by batcom** [comment]
@mytargets  那看来和php　版本也有关系，我刚刚在linux 下面5.6安装也没问题,另外一台服务器上面5.5和你报一样的错

**Comment by Mrwangzl** [comment]
同样安装处问题了：php 5.5.12 + mysql 5.6.17  + apache 2.4.9  Win10 wamp环境。
Fatal error: Uncaught exception 'gophp\exception' with message 'Class gophp\traits\call does not exist' in D:\wamp\www\phprap\gophp\library\reflect.php:38 Stack trace: #0 D:\wamp\www\phprap\gophp\library\reflect.php(54): gophp\reflect::hasClass('gophp\\traits\\ca...') #1 D:\wamp\www\phprap\gophp\library\reflect.php(80): gophp\reflect::getClass('gophp\\traits\\ca...') #2 D:\wamp\www\phprap\gophp\library\reflect.php(91): gophp\reflect::hasMethod('gophp\\traits\\ca...', 'write') #3 D:\wamp\www\phprap\gophp\library\reflect.php(156): gophp\reflect::getMethod('gophp\\traits\\ca...', 'write') #4 D:\wamp\www\phprap\gophp\library\traits\call.php(28): gophp\reflect::getMethodAccess('gophp\\traits\\ca...', 'write') #5 D:\wamp\www\phprap\gophp\library\app.php(140): gophp\log::__callStatic('write', Array) #6 D:\wamp\www\phprap\gophp\library\app.php(140): gophp\log::write('message:Call to...', 'error') #7 D:\wamp\www\phprap\gophp\library\app.php(61): gophp\app::show() #8 [internal function]: gophp\app::shutdownHandler() #9 {main} th in D:\wamp\www\phprap\gophp\library\reflect.php on line 38
